scraper:
  concurrency: 5
  max_depth: 3
performance:
  max_scroll: 8
pdf:
  ocr_enabled: true
proxies: []
crawl:
  same_domain_only: true
  exclude_query: true
  request_delay: 1
  use_robots: true
  max_retries: 3
  exclude_query_keys:
    - "utm_"
    - "ref"
    - "session"
  exclude_patterns:
    - "^javascript:"
    - "^mailto:"
    - "#"
    - "\\.pdf$"
    - "\\.zip$"
  whitelist_patterns: []
  blacklist_patterns:
    - "logout"
    - "signup"
    - "unsubscribe"
  whitelist_paths: ["/docs", "/downloads"]
  blacklist_paths: ["/login", "/logout", "/user", "/account"]
priority:
  boost_keywords:
    - "/docs"
    - "/api"
    - "/guide"
    - "getting-started"
  penalty_keywords:
    - "/legal"
    - "/terms"
    - "/privacy"
    - "/logout"
output_format: "sqlite"  # Options: csv, jsonl, json, sqlite
batch_mode: true
output_dir: "data"
db_path: "data/crawler.db"
captcha:
  mode: fallback  # Options: none, fallback, solver
  fallback_enabled: true
  snapshot_dir: "data/captcha_logs"
